name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types:
      - published

jobs:
  build:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        mode: [ Debug, Release ]

    env:
      CXX: cl.exe
      CC: cl.exe
      BUILDCACHE_COMPRESS: true
      BUILDCACHE_DIR: ${{ github.workspace }}/.buildcache
      BUILDCACHE_ACCURACY: SLOPPY
      BUILDCACHE_LUA_PATH: ${{ github.workspace }}/tools

    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      # ==== CACHE ====
      - name: buildcache Cache
        uses: actions/cache@v1.1.2
        with:
          path: ${{ github.workspace }}/.buildcache
          key: buildcache-windows-${{ matrix.mode }}-${{ hashFiles('.pkg') }}-${{ hashFiles('**/*.h') }}-${{ hashFiles('**/*.cc') }}
          restore-keys: |
            buildcache-windows-${{ matrix.mode }}-${{ hashFiles('.pkg') }}-${{ hashFiles('**/*.h') }}
            buildcache-windows-${{ matrix.mode }}-${{ hashFiles('.pkg') }}-
            buildcache-windows-${{ matrix.mode }}-
      - name: Dependencies Cache
        uses: actions/cache@v1.1.2
        with:
          path: ${{ github.workspace }}/deps
          key: deps-${{ hashFiles('.pkg') }}
          restore-keys: deps-

      # ==== BUILD ====
      - name: Build
        run: |
          $devShell = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -find **\Microsoft.VisualStudio.DevShell.dll
          $installPath = &"${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationpath
          Import-Module $devShell
          Enter-VsDevShell -VsInstallPath $installPath -SkipAutomaticLocation -DevCmdArguments "-arch=amd64"
          cmake -GNinja -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.mode }}
          .\build\bin\buildcache.exe -z
          cmake --build build --target tiles-import tiles-server tiles-benchmark tiles-test
          .\build\bin\buildcache.exe -s

      # ==== TESTS ====
      - name: Run Tests
        run: |
          .\build\tiles-test.exe
